name = "doom"
# account_id = "118553130"
# zone_id = "..."
# https://developers.cloudflare.com/workers/cli-wrangler/webpack
type = "webpack"
webpack_config = "site/webpack.js"
workers_dev = false
route = "silentspacemarine.com/*"

[site]
bucket = "./assets"
entry-point = "site"

[build]
command = "npm install"
upload.format = "service-worker"
watch_dir="./site"

